apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc
      initContainers:
        - name: pull-model
          image: ollama/ollama:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Starting temporary Ollama server to pull model..."
              ollama serve &
              sleep 5
              ollama pull llama3.1
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_KEEP_ALIVE
              value: "24h"
            - name: OLLAMA_ORIGINS
              value: "*"
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434